name = "bloggfeature"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Commented out for now until billing card details are added to Cloudflare:
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "blog-images"

[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = [ "*/5 * * * *" ]
